<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CommandLib\CommandLib.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if exist &quot;$(ProjectDir)..\FileSystemCommands\bin\$(Configuration)\$(TargetFramework)\FileSystemCommands.dll&quot; copy /Y &quot;$(ProjectDir)..\FileSystemCommands\bin\$(Configuration)\$(TargetFramework)\FileSystemCommands.dll&quot; &quot;$(TargetDir)&quot;" Condition="'$(OS)' == 'Windows_NT'" />
    <Exec Command="if [ -f &quot;$(ProjectDir)../FileSystemCommands/bin/$(Configuration)/$(TargetFramework)/FileSystemCommands.dll&quot; ]; then cp &quot;$(ProjectDir)../FileSystemCommands/bin/$(Configuration)/$(TargetFramework)/FileSystemCommands.dll&quot; &quot;$(TargetDir)&quot;; fi" Condition="'$(OS)' != 'Windows_NT'" />
  </Target>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
